---

detectors:
  DuplicateMethodCall:
    max_calls: 2
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    enabled: false # Covered by Rubocop
  NilCheck:
    enabled: false # We leverage Safe Navigation (a kind of nil check) a lot, but can't allow it specifically
  TooManyStatements:
    max_statements: 6
  TooManyInstanceVariables:
    max_instance_variables: 6
  UncommunicativeMethodName:
    accept:
      - "t" # A Rails-esque alias for translate
  UncommunicativeVariableName:
    accept:
      - "_"
      - "e"
      - "i"
      - "x"
  UtilityFunction:
    public_methods_only: true

directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    TooManyStatements:
      max_statements: 7
    UnusedPrivateMethod:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
  "app/resources":
    InstanceVariableAssumption:
      enabled: false
  "spec":
    DuplicateMethodCall:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
    UtilityFunction:
      enabled: false

# Directories below will not be scanned at all
exclude_paths:
  - db/migrate
  - tmp
